name: Plan and apply Terraform infrastructure

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy_infra.yaml
      - "terraform/**"

  workflow_dispatch:

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA }}

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: |
          ENV_VARS="{
            TARGET_PROJECT_ID = \"${{ secrets.ADP_PROJECT_ID }}\",
            OUTPUT_TOPIC = \"${{ secrets.ADP_ENRICHMENT_TOPIC }}\",
            PLATFORM_API_KEY = \"${{ secrets.PLATFORM_API_KEY }}\",
            PLATFORM_ENDPOINT = \"${{ secrets.PLATFORM_ENDPOINT }}\",
            MONGO_URI = \"${{ secrets.MONGO_URI_DRAFTS }}\",
            MONGO_DB = \"${{ secrets.MONGO_DB_DRAFTS }}\",
            MONGO_COLLECTION = \"${{ secrets.MONGO_COLLECTION_DRAFTS }}\",
            OPENAI_API_KEY = \"${{ secrets.OPENAI_API_KEY }}\"
          }"
          terraform plan -var="env_vars=${ENV_VARS}"
        working-directory: terraform

      - name: Terraform Apply
        run: |
          ENV_VARS="{
            TARGET_PROJECT_ID = \"${{ secrets.ADP_PROJECT_ID }}\",
            OUTPUT_TOPIC = \"${{ secrets.ADP_ENRICHMENT_TOPIC }}\",
            PLATFORM_API_KEY = \"${{ secrets.PLATFORM_API_KEY }}\",
            PLATFORM_ENDPOINT = \"${{ secrets.PLATFORM_ENDPOINT }}\",
            MONGO_URI = \"${{ secrets.MONGO_URI_DRAFTS }}\",
            MONGO_DB = \"${{ secrets.MONGO_DB_DRAFTS }}\",
            MONGO_COLLECTION = \"${{ secrets.MONGO_COLLECTION_DRAFTS }}\",
            OPENAI_API_KEY = \"${{ secrets.OPENAI_API_KEY }}\"
          }"
          terraform apply -auto-approve -var="env_vars=${ENV_VARS}"
        working-directory: terraform
